# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{slideshare_integration}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Darby"]
  s.date = %q{2012-02-24}
  s.description = %q{A Rails gem that streamlines interactions with the SlideShare service}
  s.email = %q{Clever.netman@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/slideshare_integration.rb",
    "lib/slideshare_integration/paperclip.rb",
    "slideshare_integration.gemspec",
  ]
  s.homepage = %q{http://github.com/MaherSaif/slideshare_integration}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{A Rails gem that streamlines interactions with the SlideShare service}
end

